# Generated by Django 4.0.6 on 2022-09-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('cilindrada', models.FloatField()),
                ('precio', models.IntegerField()),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
